workflows:
  android-debug:
    name: Android Debug APK

    environment:
      node: 22
      java: 17

    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - cd android
      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
